### PR TITLE
fix(oc-client): updated oc client to use the latest release

### PR DESCRIPTION
**Pull request by edewit**

### CODE REVIEW

**Comment by quintesse** [comment]
Could we get this looked at? It's blocking progress on our part.

**Comment by quintesse** [comment]
@rupalibehera @jaseemabid I guess this is for you guys as well, right?

**Comment by quintesse** [comment]
PS: I don't know why the check failed, but we've been successfully using the image that was built for this PR : https://hub.docker.com/r/fabric8/builder-clients/tags/  SNAPSHOT-PR-4-1

**Comment by jaseemabid** [comment]
The step that failed is PR notify and that can be ignored. I'll fix it later.

**Pull request merged**
