### PR TITLE
Add CICO files

### PR DESCRIPTION
**Pull request by chmouel**
Related: 
* https://github.com/openshiftio/openshiftio-cico-jobs/pull/820
* https://gitlab.cee.redhat.com/dtsd/housekeeping/issues/2325

### CODE REVIEW

**Comment by fabric8cd** [comment]
Snapshot builder-clients image is available for testing.  `docker pull fabric8/builder-clients:SNAPSHOT-PR-7-1`

**Comment by chmouel** [comment]
[test]

**Comment by chmouel** [comment]
https://ci.centos.org/job/devtools-builder-clients-fabric8-push-prcheck/

**Comment by fabric8cd** [comment]
Snapshot builder-clients image is available for testing.  `docker pull fabric8/builder-clients:SNAPSHOT-PR-7-2`

**Comment by fabric8cd** [comment]
Snapshot builder-clients image is available for testing.  `docker pull fabric8/builder-clients:SNAPSHOT-PR-7-3`

**Comment by fabric8cd** [comment]
Snapshot builder-clients image is available for testing.  `docker pull fabric8/builder-clients:SNAPSHOT-PR-7-4`

**Pull request merged**
